### ISSUE TITLE
i2s.h missing

### ISSUE THREAD

**Issue by revdeluxe** [revdeluxe/SPAS#1]
## Arduino ESP32 not compiling 

error occured: "I2S.h" no such file or directory found.

resource gathered:
[I2S](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP_I2S/src/ESP_I2S.h)
[I2S Documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2s.html)

solution tried:
- adding I2S.h to the work directory
_Thrown an error: I2S_PHILLIPS undefined_

possible solutions:
- fix C++ include to include I2S.

**Comment by revdeluxe** [comment]
![image](https://github.com/revdeluxe/SPAS/assets/38414584/e97c1d13-87e9-4f46-a65c-a73c566b2e22)

**Comment by Spasv3** [comment]
#include <WiFi.h>
#include <esp32-hal-i2c-slave.h>
#include <WiFiClient.h>
#include <driver/i2s.h> // Include the correct I2S driver for ESP32

// WiFi credentials
const char* ssid = "DCH-GO22-640C";
const char* password = "fc28dae7";

// Server details
const char* serverIP = "2.23.200.136";  // Replace with your server's IP address
const uint16_t serverPort = 5060;       // Replace with your server's port

WiFiClient client; 

// I2S configuration
const i2s_port_t I2S_PORT = I2S_NUM_0;
const i2s_config_t i2s_config = {
    .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),
    .sample_rate = 44100,
    .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
    .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
    .communication_format = I2S_COMM_FORMAT_I2S_MSB,
    .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
    .dma_buf_count = 8,
    .dma_buf_len = 64,
    .use_apll = false,
    .tx_desc_auto_clear = true,
    .fixed_mclk = 0
};

void setup() {
  Serial.begin(115200);

  // Initialize WiFi
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nWiFi connected.");

  // Initialize I2S for audio input
  i2s_driver_install(I2S_PORT, &i2s_config, 0, NULL);
  i2s_set_pin(I2S_PORT, NULL); // Use default pins
  i2s_zero_dma_buffer(I2S_PORT);

  // Connect to the server
  if (client.connect(serverIP, serverPort)) {
    Serial.println("Connected to server.");
    client.println("Start streaming audio");
  } else {
    Serial.println("Connection to server failed.");
  }
}

void loop() {
  // Buffer to hold audio data
  int16_t samples[512];
  size_t bytesRead;
  i2s_read(I2S_PORT, (void*)samples, sizeof(samples), &bytesRead, portMAX_DELAY);

  // Stream the audio data to the server
  if (bytesRead > 0) {
    client.write((const uint8_t*)samples, bytesRead);
  }
}
